[default]
DEBUG = false
EXTENSIONS = [
    "app.api.db:init_app",
    "app.api.migrate:init_app"
]

[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = 'sqlite:///database.db'
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    "app.api.db:init_app",
    "app.api.migrate:init_app"
]

[production]
