[default]
DEBUG = false
EXTENSIONS = [
    "app.ext.sqlalchemy:init_app",
    "app.ext.migrate:init_app",
]

[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = 'sqlite:///database.db'
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    "app.ext.sqlalchemy:init_app",
    "app.ext.migrate:init_app",
    "app.ext.marshmallow:init_app",
    "app.controllers:init_app",
    "app.ext.pydantic_spec:init_app",
    "app.ext.jwt_manager:init_app",
]

[production]
