"""modification on attribute user.escritor

Revision ID: 7de4044972b1
Revises: 0e5f8302c99a
Create Date: 2022-03-31 14:52:42.192893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de4044972b1'
down_revision = '0e5f8302c99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.Unicode(), nullable=False))
    op.drop_column('users', 'escritor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('escritor', sa.VARCHAR(), nullable=False))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
