"""empty message

Revision ID: a1a342c40aaa
Revises: 60fd4d10cef0
Create Date: 2022-03-30 12:31:41.769284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a342c40aaa'
down_revision = '60fd4d10cef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('livro', sa.Unicode(), nullable=True),
    sa.Column('escritor', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
